Repository hmcts/send-letter-service-container-new, pull requests merged in 2021-06, with the labels that each got.

#56 DTSBPS-618: nf-divorce service name correction
  src/main/resources/application.yaml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-56

#57 fix-spring-vulnerabilities
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-57

#58 Add dependabot config
  .github/dependabot.yml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-58

#71 Dtsbps 611 code optimisation
  src/main/java/uk/gov/hmcts/reform/sendletter/blob/BlobProcessor.java
  src/main/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobBackup.java
  src/main/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobReader.java
  src/main/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobStitch.java
  src/main/java/uk/gov/hmcts/reform/sendletter/config/AccessTokenProperties.java
  src/main/java/uk/gov/hmcts/reform/sendletter/exceptions/BlobProcessException.java
  src/main/java/uk/gov/hmcts/reform/sendletter/exceptions/LeaseIdNotPresentException.java
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/BlobInfo.java
  src/main/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sendletter/blob/BlobProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobBackupTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobDeleteTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobReaderTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobStitchTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorServiceTest.java
  src/test/resources/print_job_response_service_is_null.json
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-71

#72 DTSBPS-633: spring boot upgrade
  README.md
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/reform/sendletter/model/in/ManifestBlobInfo.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sendletter/model/in/ManifestBlobInfoTest.java
  src/test/java/uk/gov/hmcts/reform/sendletter/services/SasTokenGeneratorServiceTest.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-72

#76 Aded log message
  src/main/java/uk/gov/hmcts/reform/sendletter/blob/component/BlobReader.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-76

#77 DTSBPS-642: removed un-used dependencies
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-77

#78 DTSBPS-642: fix- app insight logging issue
  Dockerfile
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-78

#80 DTSBPS-642: Revert change in dockerfile
  Dockerfile
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-80

#81 DTSBPS-642: logging message in app-insight
  src/main/java/uk/gov/hmcts/reform/sendletter/Application.java
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-81
