Repository hmcts/send-letter-service-container-new, pull requests merged in 2022-05, with the labels that each got.

#201 Suppressed CVE-2021-43797
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-201

#205 Resolve CVE-2022-24823 (DTSBPS-943)
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-205

#207 Resolve CVE-2022-22970 and CVE-2022-22971
  build.gradle
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-207
