Repository hmcts/send-letter-service-container-new, pull requests merged in 2022-07, with the labels that each got.

#234 Suppress CVE-2022-33915
  charts/rpe-send-letter-service-container-new/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-234

#241 Suppress CVE-2022-31569
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-241

#246 Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-246
