Repository hmcts/send-letter-service-container-new, pull requests merged in 2022-04, with the labels that each got.

#185 Suppressed vulnerability
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-185

#186 Suppressed vulnerability
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-186

#195 Suppress vulnerabilities
  config/owasp/suppressions.xml
Labels: ns:rpe, prd:rpe, rel:rpe-send-letter-service-container-new-pr-195
